blank_issues_enabled: false
contact_links:
  - name: EvenMoreFish Discord Server
    url: https://discord.gg/Hb9cj3tNbb
    about: Check out additional support on our community discord.
  - name: EvenMoreFish Wiki
    url: https://github.com/Oheers/EvenMoreFish/wiki
    about: Check out our official documentation.
